// <auto-generated />
namespace FirmAdministartion.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addHistoryToInventory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addHistoryToInventory));
        
        string IMigrationMetadata.Id
        {
            get { return "201706231105226_addHistoryToInventory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
